const TOP_SLOGANS = [
    "Because your smile is our passion.",
    "A perfect smile guaranteed.",
    "A reason to smile.",
    "A smile is a curve that sets everything straight.",
    "An attractive smile makes a lasting impression!",
    "Be proud of your smile.",
    "Beauty is power. A smile its sword.",
    "Because teeth have feeling too.",
    "Bringing life to your smile.",
    "Care for your smile.",
    "Caring for all your family's dental needs.",
    "Comfortable & comprehensive dentistry.",
    "Committed to dental excellence.",
    "Creating beautiful smiles every day.",
    "Creating vibrant smiles for healthy lifestyles!",
    "Dental home for people in need.",
    "Dentistry is our profession, but people are our focus.",
    "Dentistry you can't wait to tell your friends about.",
    "For happy, healthy smiles.",
    "Get the smile you've always wanted!",
    "Let us brighten your smile!",
    "Make your dream smile a reality!",
    "Modern dentistry in a calm and relaxed environment.",
    "The experience you can count on.",
    "The latest in dentistry from people who care.",
    "We love to see you smile.",
    "Where smiles come alive.",
    "Your comfort is our first concern.",
    "Your smile in safe hands.",
    "Your smile matters."];
export default function getSlogan() {
    return TOP_SLOGANS[Math.floor(Math.random() * TOP_SLOGANS.length)];
}